env:
  global:
    - secure: mEjRRxfFSBWCkmq8DWJdIYIvlGoA1qthSXGWpRF8u7FlotqiOUawuMA69AwYzldoQqUCXXrZhUwy0oynIPeQmpt0Ym4SdgL4M2OK2zIWty4sqSVZvuPi3jWyziOu0yNfVXy0iJbfpucTWE6LMUWxotudWnezQVUs0RJm+wiPxBmzSWc34nNN1HiIw18TiLPDWkyzFivK4y4Gm82UZnI44qA7Cg+qTuN5/HFlx+ukCcBCKstPvSNzB81dEJTjvL8SYOVMtVd4keiJTT74qCI0/aTXkBt7ZL1yIyKV08KXF3M7V0+HloobLN5ANN04BLo2URvS2TvWcyMZrizZ8pC1qFY8kk05IoFQ0jNr9yYkV0V/srD6wO8KX9CoHDDcKrh/m2RJ3zQryqsCxAWCqWXOgIYOn13WMjyB91OX9Kg/n+JtgwyS4g7onI6k+kvKPE7WZ9KQhGXdvcUwL6qhCJJ91CuUROtl0WA9s1CP2aqrGZY23I4kG5aKML4ZTrvZluJT2nH2dcqiMhG7D8x8iDxjE6f1Ub7GEC5zxbc5qsTN+YTFcFHwyEh2oSy7wmBBqlwmro4A9nHt5+deuIDGQFhWrZ8KVztnn3lgqLBBbSIiSI+7MFVlqxIscIM1euhUyYcBmviYnWxB53DqJ+BWiJ+OR3I9S82UVUB9dVgrHYwRAFo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
