env:
  global:
    - secure: eOIj85LebCcE+FTK0SteX+tYtNkfppY9vVxMAsAWvSWWal/DfZt71x/j/gsyydd1GcdgUiFSGVLh9jVVsjPPnLMV4fBr6CeoX+9ra5QuhsuMBiIyWAoDsriCYSjEr+EHsFT83KNuF0a1Ze6pucm3XNttEq+5azigYHhEgf6qH00JzWvnIfGDBlA5YClSTMsgn4RTfuyMwZCXIzgcBiW+Sk9x0EF+tdefXbpHFeAbBIj2dMFRXx0h3c5z0wVTPWeX9BZBZzaZM/TmLhPeRUo+6WafWgUpLRaz4QJHe+x+b+kTeQV+79r7D8E3WW9pxk6o+ZOzHLbFyxt5ZE498TEddJ30Qeo8yhlaCC+XCmEha988nLhDZkFU0Hbl1OAJuQklMUyyqCjqJqUmC/pr0FiEYZ8MxZ+JkUamQ2LumoNZWfqeUyTG91Xuix83P3d4O4ga9chRhElxQHVMq2wgH6O36IXod023+Plv9WfgnylztqrgcvDzt/4lEgpJZ9NcR0/7fuV2kfAwbYW6OPgAjAdi1lKxqXgyt6eaSDQ9AkalevbIcNjCXyTrVaKAdcdcJA/ooqvfUv60BsCAJ3r3FaOAhRW2lpqQXoDVeAegoxtsROfR6IgqZ4luq9HimIVua5GUgAz+nsAGk9NARFqO2sL80qJcKIw1ZILnLK69DTHnb7Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
