env:
  global:
    - secure: SBLukgQlK+MNpnO/PGQxk883l1q7WzduvzSwdHZJ4hcf8QNlZVYj3PcVLDfZEiiWEYREt/k04zcUPc1di0OWXe/TVNWiBPvrUCDfRdp0vZouRWo19u0wYAI9QRrxEnHVY2JS3p6/rlTy4M28PKw2rG4BM2je8Llh3VYGABTujJty4P4tpNiY7YT7+AshPDTpSuRPERxKX4a5mLhSEd04+zZiqLIgJM/pf2f7QQYd5XxgcmwKQYbjX3UKEi1+NUlz8HFiYkK0twF0M+DXnm/mz4iyQ80gnQuL0qBZVnzMyJJZ7fotqaRmKtQymdDfZ1SPRD/GZ01AxjEVLk0xJZHyFDauXMn4HaMnFml9B+07/hL48tKCaZoSrLen9yXu2fzh/I6/KhrjRH2U/AeZdpS9lP3nBB4canWxQmiM7mKioPOji0sjlzqRmFmo3dzV+/xO69BJ401l8ZweQsErTmyB2uSnkR2IjYOetPVbcL5QlcsodoEO4gfPKlOneth319Ov2LuN4rCGKhRJuwNSku4R9FATWVYV6UMB3R1fsfbkc6pg3TcOTvPmclpCpqR+zMEHKiQ5z7fdOEhaaS9QSM5nggTSc6H6s9PZkSqSXyvsMvLhrJh8pA0INHBn084BeCSA5XjI05I3jkTVSJGcjvVVcINSXnupOcw8NNLSwMIE/tI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
