env:
  global:
    - secure: bvv85jNqQSnAwngIYDYXN0BdBAcH3aIorCiqZ0vCtZoqhiAn0+CnZeW6XZ4o2pjCUueXK/JUdwH9+1ZFzulSbRulm82RCOmMCSYxJ42IDLvpPamB6E5NZKTJfRaTXA2BMz64OIASMHNEyY4x2xSdcpO56bfuvXHv8n5fD5TjrXTePPV9FS4zUDRW+vRsXseZZeY8iE+djRrmgCYX5BGpp+M3D4L3UHYyZayrh1ha5MjRWnC9E3KAAUeBAdkJ6PEncyZ7NS/xBvUrgMQDDZ1MduUsGzdgqZ64WTu+ufjnbFYW9UyVYKoXgHpu0hZ5pViQwgip75y7RMr0q6PZVerYxRyXvLjU7c5ZUZnjFZJzD0g8HXsx9JVUqGdbWQNz+y56qrXsa6CyTuzeWRa9qOWppdROaAwTdzhP3RNg5B7qCa0IXwu0Dfl6Ippi2PzKwE70Cj+ytt8Jfy4RuYPmERS4RsCc1AW4865FchhPiGzXf0+75tPPb78cQWwj+p1MG+GqGtpwmoHvOvnwm7xupy4wQqgAq0kWFaTh/kVbed+X/NkY593UstayCr56CgdYNPhDebOM75pbtAFC+viTzpN+ugKes6PrXj7j8u3so0Yg6A9FU2rlKQ8OwrBSGa8I/nHuk/NjcOLop960vtVo+CNnC9R1ina+eH89MEbsi3CRsrM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
