env:
  global:
    - secure: Ye5q8e+67rWPLe/HyX+JXhD/IpRqISQTWB1LwSyYMhtHjQDpmX6sEuxYPWSojEd11WO4AKhH96eOdIgyDf91poRjoc60RGAqNOdWqKygElhN1wMMgzeCUT0UcF0CHpnUT2dVV3mU6RvZYOgdP3gVmfnmhC9fvBFsE89bFl7k8+d2bzNMVLrvS8Fni8K19p0CFS9WprcLM6jer45PmdwVqOCi/c2felHM2IXfoC0B8cxGtUJGXF1Nr71AiuaqL+Z5Jv8yKtAvW26TaF9jMxzqscdd1kzRa8VQCA3Bdzlh/SOberGWpKFJfcNKGOGY5pZ+0qIcDJGgInrLa31fhwzYh9mEvxK4ZRmcDJcdQpk61i/Rb9m57gLvIcrreJJEqO7zoRpovlv9nebl3xt8OnXedI//LbcMxOZESpIaSPkcPlxv8N9vGqar7ZDvnSEfr10TYjJwS7kMl/nugI76aFdW+1m095xCiDsfjRE6XmVDpmlhqPARYSqthYF5KWqd8BJXFaGwUQdkLOtLKk6hwOZWrwUTFTzgYS9DKtk8Dx9piGUac5W7CMU+C1Girnrn48MZF8PgcZTfWl4y6mHU80A6MLLmpK+brS04Ksny9FaRp3IuX9+DmTLbzHzWtr+7P3u3kUhhSjFxtfsRAhha9VyptSqAO2iz5aHPDMr2i3x2MEg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
