env:
  global:
    - secure: 0IenkLT+dWc+/0hssSL8fRrT3mN9nSAgFsBPjpeSsPETEYabwqwUH980uDVmWG94v+CG33ztvuS6sLq/7/7yin//yLw11FYLGBurfdGyVWLpPylHo3Zi1EPV6O99Yv4aF8tqfoBNtvZQZniIB+11fK849Y//DE4AoS3iD2e/vWLguyg14jE+7QCmMcKdwwiyogGfHKmIGxw4mnl7izHCw/HJ+7m5i86Kd7K0BpFP4O10S/4BqwlczeP2zggfUMlKzVYaxOPHy1zN5i56jaKjHcG3sisji2JT4F67+o7rER77A9QKalO9KApLXlQ54MzlM6vAMoO/GfiNAUqAYKcDCsx1v7c3UJCOMdTjWS+3RTWmJTd1FqBvIn338GO2plXB8yOcYW39rrAQWpb2UHXYv7tT+JVCanve/OeYa07vugROPnPsofKtR7/OGLQpq4lh6MSNOSyN9fXDSv2siBPy2c34EnKZB5xcikFzjoBMREPGjLBuMfvFK+YEpHceMqgBz5Bm/QPE9eobJOcbKbDbpF16Ft0XZwTAot/rotQtvrMe2aaIzgW0WyScM1jNnKVY4kbjJkXkbIv2wpihQAUUNNSXxzde/ooB4QXXg1mOU5J6VjR5wDoviInJuwwNGQXbxluS4WapAKIKiVXkajFG0OT0wwvsb2VlNey1QviPPRk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
