env:
  global:
    - secure: 5+AgqmYMjyMAhFMTKsmi0P8YYUzweyNY/uULwzHpt6CBdQ3NptQ7cvNQhdrRw+FdBJoBTk51Rqood+Tlo1/K9P4lhtoVJwhbcs6kQynxRSz1Q1Uj3QCuF3NytoGmNG4s8QtwbO0gZTs5IBYZ3+3MoWLt3u7NFZqW8xExsCm4TZa576+QOHPsJHRgfL1mpMd/g+4hGY7qYuKRw1csME7mowTkqyJS3IIJQBVvbgP1ip05pshhe82Z3Z1L6F4bP6Lt0fNb3u0+EW5Wi7lVH8Vrq4USGP5RmN9WksgJ9KxeRl/f3JdIV7dwmQbo2DWqDbS0RwC92PKLd1QHsPd0dBQd1rvmJdWWdW4ZUA3K2c1pUC4DIP3vdSbCU23FsxYPp4EZUyKTX0uKmxB5cQnYx1iJFCtWe7uSzq2nzBz93IX/r1gEZp3BlczrOzd6G3qQ33T0n+eBUWv7KYyCosbXIIErjzxu0ElNkxPIiJSzXpg8eXvD9ifG3++D6wAS+856UrUaHNmKJ6Df/Rq23fjbYsS4b476qGf0+d6A9jY1LGZn/mcWfMGKgBPzyivoyP9TsItg7j30RJbOE9C65X5M4It8fwhjNosO4G4jLfD7KyT78/MPsdETTi+DH5M/FyvKUMmJ6Ms+bHRqVGlYEJ4yqaR/HOILnYzOP01P5iPlA+L+SdA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
