env:
  global:
    - secure: oayf3MVN8OOtAf38m2W8k+jg3DBp2oV3bSz5mZv6Iv/GqVFJlYv4b04WsK9gWFdpdJqR/PetRPVLoi26CClldJZb2RuCrnHgP/DfI+AZiSbu+sITvYf0eAEZkUXfV4csDOgFkg/VXoq9EURbIzBSH8wnAWlii1oImkLim9qgwOOf6WOp53K6SxuoLmMkS6N4dnCCLu+R5HiSkbpNKrjVMwmpuPIwyFwh1ggxFKv2R206CvQXJNZugLCQpyFPl89e5IarTd6UNKz01hWcNFI5E9rLANog6sidYRyNTDRiMeyjzVYIbDBmSZIafO9CvB7sqB181iiXd8sBe7qcdNUnclAyzQVzKHSgLdKz43Qrm8ICpxu4G2MmTAdTk9k+H4gTwocjlAYeXuyNt0ldkYVSy8yCNeiCOcGv7/gXhuyd7hYz0jFFSPXhrzUWf8R3mrr+eYQ3FJO3U2QHo7VI60Cel1HRaqiAWh5eYJVCSkv6Op82eKK0XPETYDzUKpyujWzgUqcY4EnWmEGY0pMLL4RfV40n3MD5GTAuPjjdbcdmIBnEUxCCEmFHJ/7p0BSY6h8Ge5L7uQsj452Bx3232SwiMvL6WJgMmoxZObGN6w/x/ijTsrRMbQVY/HagoGLnsWJWqORWNKs0RY164sC2fdCkzO005k3kgoEJ8qXBE2nz6lc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install dead-hosts-launcher

script:
  - dead_hosts_launcher


notifications:
  email:
    recipients:
      - dead-hosts@funilrys.com
    on_success: never
    on_failure: always
