env:
  global:
    - secure: KMBPRdm1wqeVcMFxpVc1xFOtzs5vQx89BbnvrI4nbhr6OCudwfiGVU1vdPmL0xGWnW7oL0x/M3+ddbWx0RdrkLJd5GZ02AmOeW3ZgejZuMG2ZGH+CIdjq2R5gTDLZJBx9cZ96gZm3aH7/jK0s0rc8CrwAvlLeYn3CkqB1QCxSz/JnPGxru84fyBhj7Wqjc9rHkzdED5spytbcPoGUTbeD0YV1V6XjMJFCNuP2pLUafxlZTKr+uZe/rIniradj4/+dtoMFSqyPYYiW6K3t4dV8rzBwoQQ09jyVUcI8mqa41+tOGBX+WNo/NcpkjFmib33NTIz5Tx7BxHgZ+dj2Sn7lJb5wplYoimCAUtXmWOCk7pSx0q6kcw7NDbUxPqVxVdMwxkNqMQV8dsLhNEcD/fzVv7FIICrZmj5Kbzi08kayJYBnUBrYlX8MV6aifV4NLSNA5Wj7BvI2Dz1ToJ/GFb5AiAFmvFAVaUiKuQCPOQtTAcp6k220z3acOGfrh1sFven0EEsbYdjMG+Qk3Sl7snC+2xgZOQpWUBEyKinAnNKDa8uYPpGsdQnQ0x/4FWslHWtM9F0xN7CDmCmriN0WNkMEMYhogzYLpHDCPKraFCZAjHBOqoKnL0maAAh7Zua1ywGhDC2jlD9xVwEos90tPSpadTR0MCujnjpwdxUp67STKo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
