env:
  global:
    - secure: kDH0mh391fgdo2YkZ6VriB/EEcFMnaxqUF+7D0KjqukTGnvO4hX5UxVJ+WJo+6oDldE+uluIPwi1LZ3OMTUV8GtmJ1rvT8RkvGQmQnxl5GiMJPTOA+agBxBZyBm6fjP8F1i7PR9ib7cS1OtovQMVFmtQZc98wKYShBfjHKsEJQOIVKGltPOI8/Jqr39/L5Wja0eIPASUhuj/mRyKT9xlUWJtUlGjAFDrXCxft/AfS/k6L2ivOUFZdEeiXdBCOcgNBA/UQU//MvJ/h5cXdEqKYn6pgBefrzgz3sBcfRUqQ2n+MAM5VWKsaiEJpwsizBLozZzgS0B+VHYDXU3hfNqjQtorpXihXoAxgWCyy8stGaCUC1TqYJbDzCGnjgVBzSt56B2Bxah2S31noA+bpxacBn/93FgDwBWSZVfDtZSQSb3UTMdIo+ar799t0xly+408/SIN9Z8ltAPbQ8FtyHE9Mvm+Pgw6sr4Hv/IUKXEh6E3hzXj53RBmvqpxqI6lpwdmQ3l3kWL03M1Qiq0kOow1HIgnbVf9U8IGTBgaMFOn6qJ0OZ8zrI9yobUlB+Kl4Y/8DxQJTWeOUxrKj/yyIcyIKJVLVcvsGWQ+So1zMUgDQdpV82c+8KqlZUb/7PfwBBngd6SuCqLSxPIT7dpKpE20azaHbWuIItgT3HHH+J9iw4c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/add.Dead_git_FadeMind
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
